import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { GoogleAnalytics } from '@next/third-parties/google'

const urbanist = Urbanist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-slate-100 text-slate-900">
      <GoogleAnalytics gaId="G-STJWHCEVQL" />
      <body className={urbanist.className}>
        <Header />
        {children}</body>

    </html>
  );
}
